test:rocm_vega20:
  extends: .rocm
  stage: test
  needs:
    - !reference [.rocm, needs]
    - build:rocm
  tags:
    - vega20
    - rocm
  script:
    - cd build
    - $SUDO_CMD ctest --output-on-failure

test:rocm_s9300:
  extends: .rocm
  stage: test
  needs:
    - !reference [.rocm, needs]
    - build:rocm
  tags:
    - s9300
    - rocm
  script:
    - cd build
    - $SUDO_CMD ctest --output-on-failure
  allow_failure: true

test:rocm_mi25:
  extends: .rocm_static
  stage: test
  needs:
    - !reference [.rocm_static, needs]
    - build:rocm-static
  tags:
    - mi25
    - rocm
  script:
    - cd build
    - $SUDO_CMD ctest --output-on-failure
