# MIT License
#
# Copyright (c) 2017 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

variables:
  SUDO_CMD: "" # Must be "sudo" on images which dont use root user
  DEPS_DIR: "$CI_PROJECT_DIR/__dependencies"
  CMAKE_URL: "https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz"
  # General build flags
  CXXFLAGS: ""
  CMAKE_OPTIONS: ""
  # Local build options
  LOCAL_CXXFLAGS: ""
  LOCAL_CMAKE_OPTIONS: ""
  ROCM_LATEST_PATH: "/opt/rocm-4.5.0"

stages:
  - deps
  - build
  - test

# ROCm

.setup_rocm:
  variables:
    SUDO_CMD: "sudo -E"
    SUDO_CMD_HOME: "sudo -E -H"
  tags:
    - rocm
  image: rocm/rocm-terminal:latest
  before_script: &setup_rocm
    - $SUDO_CMD apt-get update -qq
    - $SUDO_CMD apt-get install -y -qq libidn11 git wget tar xz-utils bzip2 build-essential pkg-config ca-certificates kmod gfortran findutils
    - hipconfig
    # cmake
    - mkdir -p $DEPS_DIR/cmake
    - wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $DEPS_DIR/cmake
    - export PATH=$DEPS_DIR/cmake/bin:$PATH
    # Combine global build options with local options
    - export CXXFLAGS=$CXXFLAGS" "$LOCAL_CXXFLAGS
    - export CMAKE_OPTIONS=$CXXFLAGS" "$LOCAL_CMAKE_OPTIONS
    - export ROCM_PATH=/opt/rocm

# Build rocRAND package from source to be used by other jobds
deps:rocrand:
  stage: deps
  extends: .setup_rocm
  variables:
    ROCRAND_GIT_BRANCH: "develop_stream"
  script:
    - branch_name="$ROCRAND_GIT_BRANCH"
    - if [ $CI_COMMIT_BRANCH == develop ] || [ $CI_COMMIT_BRANCH == master ]; then branch_name=$CI_COMMIT_BRANCH;
    - fi;
    - git clone -b $branch_name https://gitlab-ci-token:${CI_JOB_TOKEN}@${ROCRAND_GIT_URL}
    - cd rocRAND
    - mkdir build
    - cd build
    - cmake
      -D CMAKE_CXX_COMPILER=hipcc
      -D CMAKE_BUILD_TYPE=Release
      -D BUILD_TEST=OFF
      -D BUILD_EXAMPLE=OFF
      -D ROCM_DEP_ROCMCORE=OFF
      ../.
    - cmake --build . --parallel 16
    - $SUDO_CMD cpack
      -G "DEB"
  artifacts:
    paths:
      - rocRAND/build/rocrand*.deb
    expire_in: 2 weeks

.install_rocrand: &install_rocrand
    - $SUDO_CMD dpkg -i rocRAND/build/rocrand*.deb
    - find -L $ROCM_PATH | grep rand | sort

.rocm:
  extends: .setup_rocm
  needs:
   - deps:rocrand
  before_script:
    - *setup_rocm
    - *install_rocrand

build:rocm:
  extends: .rocm
  stage: build
  script:
    - mkdir build
    - cd build
    - CXX=hipcc cmake -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON -DBUILD_FORTRAN_WRAPPER=OFF -DDEPENDENCIES_FORCE_DOWNLOAD=ON ../.
    - make -j16
    - make package
  artifacts:
    paths:
      - build/library/
      - build/test/crush_test_*
      - build/test/test_*
      - build/test/stat_test_*
      - build/test/CTestTestfile.cmake
      - build/benchmark/benchmark_*
      - build/gtest/
      - build/testu01/
      - build/CMakeCache.txt
      - build/CTestTestfile.cmake
      - build/*.deb
      - build/*.zip
    expire_in: 2 weeks

build:rocm-static:
  extends: .rocm
  stage: build
  script:
    - mkdir build
    - cd build
    - CXX=hipcc cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON -DBUILD_FORTRAN_WRAPPER=OFF -DDEPENDENCIES_FORCE_DOWNLOAD=ON ../.
    - make -j16
    - make package
  artifacts:
    paths:
      - build/library/
      - build/test/crush_test_*
      - build/test/test_*
      - build/test/stat_test_*
      - build/test/CTestTestfile.cmake
      - build/benchmark/benchmark_*
      - build/gtest/
      - build/testu01/
      - build/CMakeCache.txt
      - build/CTestTestfile.cmake
      - build/*.deb
      - build/*.zip
    expire_in: 2 weeks

include: '.gitlab-ci-gputest.yml'

test:rocm_python:
  extends: .rocm
  stage: test
  needs:
    - !reference [.rocm, needs]
    - build:rocm
  tags:
    - rocm-stable
  before_script:
    - *install_rocrand
    - $SUDO_CMD apt-get update -qq
    - $SUDO_CMD apt-get install -y -qq python python-pip python-numpy
    - $SUDO_CMD apt-get install -y -qq python3 python3-pip python3-numpy
    - $SUDO_CMD apt-get install -y -qq wget
    - $SUDO_CMD apt-get -y remove python-pip python3-pip
    # Latest supported Python version of pypa is 3.6, but there's no permalink
    # for the latest scripts, hence the '+' in the filename and the generic URL
    - wget https://bootstrap.pypa.io/get-pip.py -O get-pip-3.6+.py
    - wget https://bootstrap.pypa.io/pip/2.7/get-pip.py -O get-pip-2.7.py
    - $SUDO_CMD_HOME python get-pip-2.7.py
    - $SUDO_CMD_HOME python3 get-pip-3.6+.py
  script:
    - export HIPRAND_PATH=$CI_PROJECT_DIR/build/library/
    # hipRAND Wrapper with Python 2
    - cd $CI_PROJECT_DIR/python/hiprand
    - $SUDO_CMD python2 setup.py test
    - pip2 install . --user
    - $SUDO_CMD python2 tests/hiprand_test.py
    - pip2 uninstall --yes hiprand
    # hipRAND Wrapper with Python 3
    - cd $CI_PROJECT_DIR/python/hiprand
    - $SUDO_CMD python3 setup.py test
    - pip3 install . --user
    - $SUDO_CMD python3 tests/hiprand_test.py
    - pip3 uninstall --yes hiprand

test:rocm_package:
  extends: .rocm
  stage: test
  needs:
    - !reference [.rocm, needs]
    - build:rocm
  tags:
    - rocm-stable
  script:
    - cd build
    - $SUDO_CMD dpkg -i hiprand*.deb
    - mkdir ../build_package_test && cd ../build_package_test
    - CXX=hipcc cmake ../test/package/.
    - make VERBOSE=1
    - $SUDO_CMD ctest --output-on-failure
    - ldd ./test_hiprand
    - $SUDO_CMD dpkg -r hiprand

test:rocm_install:
  extends: .rocm
  stage: test
  tags:
    - rocm-stable
  script:
    - mkdir build_only_install
    - cd build_only_install
    - CXX=hipcc cmake -DBUILD_TEST=OFF -DBUILD_FORTRAN_WRAPPER=OFF ../.
    - make -j16
    - $SUDO_CMD make install
    - find -L $ROCM_PATH | grep rand | sort
    - mkdir ../install_test && cd ../install_test
    - CXX=hipcc cmake ../test/package/.
    - make VERBOSE=1
    - $SUDO_CMD ctest --output-on-failure
    - ldd ./test_hiprand


# NVCC

.nvcc:
  tags:
    - nvcc
  image: nvidia/cuda:11.4.1-devel-ubuntu18.04
  before_script:
    - nvidia-smi
    # HIP-nvcc
    - $SUDO_CMD apt-get update -qq
    - $SUDO_CMD apt-get install -y -qq ca-certificates git wget tar xz-utils bzip2 build-essential pkg-config g++ gfortran findutils
    - wget -qO - https://repo.radeon.com/rocm/rocm.gpg.key | $SUDO_CMD apt-key add -
    - echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ ubuntu main' | $SUDO_CMD tee /etc/apt/sources.list.d/rocm.list
    - $SUDO_CMD apt-get update -qq
    - $SUDO_CMD apt-get install -y hip-dev rocm-cmake
    # Install hip-nvcc ignoring dependencies because it depends on cuda metapackage
    # (with heavy libraries, tools etc. that also require GUI and other packages)
    - apt-get download hip-runtime-nvidia
    - $SUDO_CMD dpkg -i --ignore-depends=cuda hip*.deb
    - $SUDO_CMD ls -d /opt/*
    - $SUDO_CMD ln -s $ROCM_LATEST_PATH /opt/rocm
    - export PATH=$PATH:/opt/rocm/bin
    - hipconfig
    # cmake
    - mkdir -p $DEPS_DIR/cmake
    - wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $DEPS_DIR/cmake
    - export PATH=$DEPS_DIR/cmake/bin:$PATH
    # Combine global build options with local options
    - export CXXFLAGS=$CXXFLAGS" "$LOCAL_CXXFLAGS
    - export CMAKE_OPTIONS=$CXXFLAGS" "$LOCAL_CMAKE_OPTIONS
    - export ROCM_PATH=/opt/rocm

build:nvcc:
  extends: .nvcc
  needs: []
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON -DBUILD_FORTRAN_WRAPPER=OFF -DDEPENDENCIES_FORCE_DOWNLOAD=ON -DNVGPU_TARGETS="52;70" ../.
    - make -j16
    - make package
  artifacts:
    paths:
      - build/library/
      - build/test/crush_test_*
      - build/test/test_*
      - build/test/stat_test_*
      - build/test/CTestTestfile.cmake
      - build/benchmark/benchmark_*
      - build/gtest/
      - build/testu01/
      - build/CMakeCache.txt
      - build/CTestTestfile.cmake
      - build/*.deb
      - build/*.zip
    expire_in: 2 weeks

test:nvcc_titanv:
  extends: .nvcc
  stage: test
  needs:
    - build:nvcc
  script:
    - export CUDA_VISIBLE_DEVICES=0
    - cd build
    - $SUDO_CMD ctest --output-on-failure

test:nvcc_980:
  extends: .nvcc
  stage: test
  needs:
    - build:nvcc
  script:
    - export CUDA_VISIBLE_DEVICES=1
    - cd build
    - $SUDO_CMD ctest --output-on-failure

test:nvcc_python:
  extends: .nvcc
  stage: test
  needs:
    - build:nvcc
  before_script:
    - $SUDO_CMD apt-get update -qq
    - $SUDO_CMD apt-get install -y -qq python python-pip python-numpy
    - $SUDO_CMD apt-get install -y -qq python3 python3-pip python3-numpy
    - $SUDO_CMD apt-get install -y -qq wget
    - $SUDO_CMD apt-get -y remove python-pip python3-pip
    # Latest supported Python version of pypa is 3.6, but there's no permalink
    # for the latest scripts, hence the '+' in the filename and the generic URL
    - wget https://bootstrap.pypa.io/get-pip.py -O get-pip-3.6+.py
    - wget https://bootstrap.pypa.io/pip/2.7/get-pip.py -O get-pip-2.7.py
    - $SUDO_CMD_HOME python get-pip-2.7.py
    - $SUDO_CMD_HOME python3 get-pip-3.6+.py

  script:
    - export ROCRAND_PATH=$CI_PROJECT_DIR/build/library/
    # hipRAND Wrapper with Python 2
    - cd $CI_PROJECT_DIR/python/hiprand
    - $SUDO_CMD python2 setup.py test
    - pip2 install . --user
    - $SUDO_CMD python2 tests/hiprand_test.py
    - pip2 uninstall --yes hiprand
    # hipRAND Wrapper with Python 3
    - cd $CI_PROJECT_DIR/python/hiprand
    - $SUDO_CMD python3 setup.py test
    - pip3 install . --user
    - $SUDO_CMD python3 tests/hiprand_test.py
    - pip3 uninstall --yes hiprand

test:nvcc_package:
  extends: .nvcc
  stage: test
  needs:
    - build:nvcc
  script:
    - cd build
    - $SUDO_CMD dpkg -i rocrand*.deb
    - find -L $ROCM_PATH | grep rand | sort
    - mkdir ../build_package_test && cd ../build_package_test
    - cmake ../test/package/.
    - make VERBOSE=1
    - $SUDO_CMD ctest --output-on-failure
    - ldd ./test_hiprand
    - $SUDO_CMD dpkg -r rocrand

test:nvcc_install:
  extends: .nvcc
  stage: test
  needs: []
  script:
    - mkdir build_only_install
    - cd build_only_install
    - cmake -DBUILD_TEST=OFF -DBUILD_FORTRAN_WRAPPER=OFF ../.
    - make -j16
    - $SUDO_CMD make install
    - find -L $ROCM_PATH | grep rand | sort
    - mkdir ../install_test && cd ../install_test
    - cmake ../test/package/.
    - make VERBOSE=1
    - $SUDO_CMD ctest --output-on-failure
    - ldd ./test_hiprand

test:doc:
  variables:
    SUDO_CMD: "sudo -E"
  tags:
    - rocm # Do it on rocm machine
  image: rocm/rocm-terminal:latest
  stage: test
  needs: []
  before_script:
    - $SUDO_CMD rm /etc/apt/sources.list.d/rocm.list
    - $SUDO_CMD apt-get update -qq
    - $SUDO_CMD apt-get install -y -qq doxygen python3-sphinx python3-pip
    - $SUDO_CMD -H pip3 install numpy
  script:
    - cd doc
    - $SUDO_CMD doxygen Doxyfile
    - $SUDO_CMD make -C ../python/hiprand/docs html